export * from './auth';
export * from './dashboard';
export * from './classfitness';
export * from './exercise';
export * from './mybooking';
export * from './trainer';
export * from './mytrainer'
export * from './account';
export * from './trainerschdule';
export * from './backoffice';
export * from './backofficetrainer';
export * from './try'
export * from './bmiinfo'
export * from './history'