export * from './admin';
export * from './user';
export * from './edituser';
export * from './adminclass';
export * from './adduser';
export * from './editclass';
export * from './viewclass';
export * from './deluser'
export * from './modul'